### ISSUE TITLE
joining with ports should include slashes

### ISSUE THREAD

**Issue by charleshansen** [yanni4night/urljoin#1]
When I try `urljoin('localhost:3000', 'main.css')` I expect 'localhost:3000/main.css', but I instead get 'localhost:3000main.css'. It seems the ':' makes it think there is a protocol there and changes the behavior. 

Not a huge deal, but I thought you'd be interested if you are still maintaining this library.

**Comment by yanni4night** [comment]
As you say, `localhost` is parsed as a protocol, and `3000` as a host. That's reasonable. Some protocols do have no slashes('//' or '/') at all, _mailto:_ e.g. When formatting, these protocols just discard  slashes.

I suggest you to prepend a 'http://' like protocol. It should work.

See [L613](https://github.com/nodejs/node/blob/v6.4.0/lib/url.js#L613) in **lib/url.js** for more details.
